Conditionally set instruction for tryAssembler based on wavefront
ROCm/Tensile pull request #1986
Opened 2024-07-25 14:05 UTC by ellosel

When using a wavefront size of 64, we should pass the following instruction to `tryAssembler`:

```
"v_wmma_f32_16x16x16_f16 v[0:3], v[8:15], v[16:23], v[0:3]"
```

when using using a wavefront size of 32 we should use:

```
"v_wmma_f32_16x16x16_f16 v[0:7], v[8:15], v[16:23], v[0:7]"
```

2024-07-25 15:35 UTC, yoichiyoshida requested changes

2024-07-25 15:35 UTC, yoichiyoshida commented on Tensile/Common.py
> +
we're either setting this flag or not for the tests, we should pick one or the other, instead of a redundant conditional

2024-07-26 12:43 UTC, babakpst approved these changes

2024-07-26 15:19 UTC, babakpst commented
@yoichiyoshida Can you please review this PR again? Thanks.

2024-07-26 15:20 UTC, yoichiyoshida reviewed
lgtm

2024-07-26 15:27 UTC, babakpst commented
Good, can you please remove the change request, so that I can merge it?

2024-07-26 15:57 UTC, nakajee commented
@yoichiyoshida 
I think you need to approve this PR to remove change request.

2024-07-26 16:35 UTC, yoichiyoshida approved these changes

2024-07-26 16:37 UTC, merged